### ISSUE TITLE
Progeny with permutations changes CARNIVAL results each time

### ISSUE THREAD

**Issue by IvanEllson** [saezlab/transcriptutorial#19]
Hello, I've been following the tutorial and I've realised that, when using progeny (>1 permutation), the results of the network are not allways the same. This is because the result of progeny function sighly changes if you select more than one permutation (perm=10000 in the tutorial). In the other hand, selecting more than one permutation allows you to get a result between -1 and 1 (if i'm not mistaken). 
If I select 1 permutation I end up getting values from -1500 to 500 (even if setting z_scores=FALSE), and the CARNIVAL runCARNIVAL function doesn't accept such pathway scores (only -1 to 1 values are accepted), but if I select more permutations the results change everytime.
My solution was to avoid using my pathway scores as weightObj in CARNIVAL.
Is there any way of using progeny scores in CARNIVAL so it doesn't change the solution every time I run it?

Thank you!

**Comment by adugourd** [comment]
This is because the permutation approach to normalise the score is a stochastic process, so it will give slightly different results everytime. In theory, with 10000 permutations, these differences should be really minimal and not impact the results.

Thus, there is no way to always get the same normalised score from progeny at the moment.

**Comment by gabora** [comment]
Actually, if you set the same seed for the random number generator (`?set.seed()`) before calling the progeny function, then you should have identical results.

**Comment by IvanEllson** [comment]
Ok, thank you for your answers!
