### ISSUE TITLE
Cplex solver in part 05

### ISSUE THREAD

**Issue by clohoff** [saezlab/transcriptutorial#28]
At the beginning of tutorial part 05 it should be mentioned that the cplex solver must be installed for running CARNIVAL.
For running cplex in Windows I had to add ".exe" to solverPath: 
solverPath = "/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx/cplex.exe",

**Comment by rachel662** [comment]
Hi, i have tried this but I still get this error:

Error in checkSolver(solverPath = solverPath, solver = solver, dir_name = dir_name) : 
Please provide a valid path to interactive solver

Do you have any more advice on how to get round this? 
Cheers
Rachel

**Comment by gabora** [comment]
Hi Rachel, 

here is how my code looks like:
```r
carnival_optim_results = runCARNIVAL(inputObj = carnival_inputs$inputs,
					measObj = carnival_inputs$measurement,
					netObj = carnival_inputs$sif,
					betaWeight = 0.001,
					solver = 'cplex',
					solverPath = "/Applications/CPLEX_Studio128/cplex/bin/x86-64_osx/cplex")
```
This works on my Mac, with my version of CPLEX. 
Which operation system do you use? 
Did you check that the `solverPath` is correct for your version of CPLEX?  (try to navigate to the `solverPath` folder and check if the cplex executable is there)

**Comment by rachel662** [comment]
Hi 
thanks so much for your help
I'm not sure I'm finding the solverPath folder? 

The bit which my code fails at is this bit 
![image](https://user-images.githubusercontent.com/63318678/135617863-fe0f83e7-c198-4da0-be59-07db1488e406.png)

thanks for your help 
Rachel

**Comment by gabora** [comment]
Hello, 

do you work on Mac, linux or Windows? 
did you download the CPLEX from IBM? (CPLEx is a commercial software which is free for academic use, https://www.ibm.com/products/ilog-cplex-optimization-studio) 
The website seems not fully functional at the moment, but this happened also in the past for a few days. 
If you dont have CPLEX, you can try with CBC (please also obtain it from: https://github.com/coin-or/Cbc/releases) or Gurobi (it is also commercial software but free for academia)

**Comment by rachel662** [comment]
Ah no I didn't download it, I work on windows 
Does it matter what folder you download it do as long as the path to it is set correctly? 

thanks again 
Rachel

**Comment by gabora** [comment]
OK:) 
no, it does not matter where you install it as long as you set the directory correctly. 

Since the download page seems not working, I would like to mention that Gurobi (https://www.gurobi.com/academia/academic-program-and-licenses/) is also available as a solver. It is also commercial, but free for academia and maybe it is even better than CPLEX (evaluation is still in progress).
 
To work with Gurobi, please install the most recent CARNIVAL from our github repo, for example, like this: 
```r
remotes::install_github("saezlab/CARNIVAL")
```

This got recently integrated as a solver for CARNIVAL and the documentation is still need to be done. I just recognised this and opened an issue on the CARNIVAL repository. 
But in the end,  you just have to select "gurobi" as solver and provide a path to the gurobi executable, same as CPLEX. 

hope this helped. 
best,
Attila
